### ISSUE TITLE
Allow worldguard region to be discovered

### ISSUE THREAD

**Issue by RedSmarty** [AtriusX/Waystones#19]
I would like to see a feature in which when a player enters a worldguard region, it automatically gets the option to warp to a lodestone of that particular area. (Set by the user)

**Comment by AtriusX** [comment]
Thanks for your interest in the project! I don't really know if something like this is in the scope of the plugin through. Our only real purpose for linking with various protection plugins is to make sure Waystones can't be used where people or server admins don't want them to be.

With that said, If someone wanted to implement something like this on top of Waystones I don't see why it shouldn't be possible. Some changes might need to be made in order to account for this to work but it's an option.

**Comment by AtriusX** [comment]
Closing this issue now, any discussion in regard to the plugin's API should be directed to discussion #22.
