### ISSUE TITLE
link-no-permission: This link has severed and rotted away...

### ISSUE THREAD

**Issue by deadlylaser0** [AtriusX/Waystones#35]
friend made a waystone and when he tries to link it says link-no-permission: This link has severed and rotted away...

**Comment by AtriusX** [comment]
Sorry for the late reply! I've been a bit busy as of late, but that error should occur if the person trying to link the warp key does not have the permission `waystones.link`. This was a small oversight on my part since it isn't listed in the project readme or spigot page I believe. I'll get around to updating those shortly.

As far as the error message is concerned, is it printing "link-no-permission" with the error? If so I would love to see some screenshots of it happening. Thanks!

**Comment by deadlylaser0** [comment]
I downloaded this plugin from apex hosting and there's not exactly any screen shots to show . When NON operator people try to link it just says the link has been severed in game

**Comment by AtriusX** [comment]
I see, so the only thing you'd need to do to fix this issue then is to simply give the `waystones.link` permission to everyone. I might update this later so it doesn't require this, at least by default. But for now that solution should work.

**Comment by AtriusX** [comment]
Alright, I've updated the spigot page so that it now shows the missing permissions.

**Comment by AtriusX** [comment]
As of https://github.com/AtriusX/Waystones/releases/tag/1.1.0 the `waystones.link` should now be given to players by default.
