### ISSUE TITLE
Teleportation (somewhat) broken for Server Operators

### ISSUE THREAD

**Issue by TonyKuroi** [AtriusX/Waystones#46]
Hello,

I've been using this plugin without issue for several days and things have been pretty great. Suddenly, today, with no changes or updates, waystones has been... misbehaving. I've posted an example to youtube.

https://youtu.be/0v78yIKFtOc

A rundown of the issue is as follows:
Right Clicking attempts to teleport you to some number of blocks in front of where your cursor is. This is shown when I am teleporting but my compass is not moving.
Left Clicking does... something. I'm honestly not sure exactly where it's teleporting me to. That is when it moves the compass.

Both of these things only happen when I'm server operator. As shown in the video, deopping fixes the issue. ReOpping breaks it again. 

I tried to compile the plugin myself locally so that I could try to debug it myself, however I cannot get the resulting jar to run. I'm opening it in IntelliJ and using the provided gradle settings to generate the Jar. the resulting error is as below. 

> java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
>         at xyz.atrius.waystones.WaystonesKt.setPlugin(Waystones.kt) ~[waystones-1.1.0.jar:?]
>         at xyz.atrius.waystones.Waystones.onEnable(Waystones.kt:25) ~[waystones-1.1.0.jar:?]
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.18.1.jar:git-Paper-71]
>         at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.18.1.jar:git-Paper-71]
>         at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-71]
>         at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-71]
>         at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-71]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-71]
>         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-71]
>         at java.lang.Thread.run(Thread.java:833) ~[?:?]
> Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
>         at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
>         ... 13 more

Server is PaperMC 1.18.1 using your latest plugin 1.1.0. Server OS is Debian based, MineOS. Java version is OpenJDK version 17.0.1. 
Local dev machine is Arch Linux, openjdk 17.0.1

Can you 
1. create a section of your readme that explains your environment setup/how to set up to help contribute if someone would like to? and/or 
2. let me know what would I can do to help debug this issue, if anything further than already done. 

Thanks

**Comment by AtriusX** [comment]
Hey @TonyKuroi! Thanks for your report. We use a specific task for compiling since we need to embed Kotlin directly into the plugin for it to work. To do this you need to run the `shadowJar` task instead of the `build` task. This is the same issue that was worked out in #2.

Based on what I'm seeing in your video, you appear to be running WorldEdit and Waystones together? WorldEdit has a compass feature that allows you to teleport around by right clicking while facing a specific direction. Since our plugin also uses compasses with a similar control set, what's actually occurring is that WorldEdit is taking event precedence over Waystones. The reason why it only breaks for operators in your case is likely because only operators are granted permission to use the compass in WorldEdit.

At the moment, I do not know if this is an issue we can directly fix or not. If you want you can try to debug the plugin locally with the compiler task I listed above. The only suggestion I can give is to maybe mess with the event priority on the teleport actions in the plugin.

For quick fixes to the problem, you can try to disable the compass in WorldEdit, or check if its possible to reconfigure the item used so that it no longer overlaps. Hope this helps!

**Comment by TonyKuroi** [comment]
Ah, it _was_ worldedit! That makes sense. Honestly, I wasn't aware my roommate installed that :) 

I'll still look into setting up the build pipeline because I can. But thanks for the help!

**Comment by AtriusX** [comment]
No problem! If you manage to find a way to make it work with WorldEdit without changing the compass to something else, feel free to submit a PR for it!
